services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - "8181:8181"
    depends_on:
      - db
  db:
    image: "mysql:lts"
    restart: always
    environment:
      MYSQL_DATABASE: library
      MYSQL_ROOT_PASSWORD: root1234
    volumes:
      - ./datasql:/var/lib/mysql